In [1]:
import torch
import numpy as np 

In [6]:
print('hello pytorch {}'.format(torch.__version__))
print('cuda is available {}'.format(torch.cuda.is_available()))

hello pytorch 2.0.1
cuda is available False


torch.autograd.Variable:

data:被包装的Tensor

grad:data的梯度

grad_fn:创建Tensor的Function 是自动求导的关键

requires_grad:指示是否需要梯度

is_leaf:指示是否是叶子结点

Pytorch 0.4.0之后 Variable并入Tensor

torch.Tensor:

dtype:

张量的数据类型 如torch.FloatTensor,torch.cuda.FloatTensor     

用的最多的是torch.float32  卷积层的权值 图像预处理之后

torch.long/int64 图像标签

shape:张量的形状，如(64，3，224，224)

device:张量所在设备 GPU/CPU

同上
data  grad  grad_fn  requires_grad  is_leaf

张量的创建

1.直接创建 

1.1torch.tensor() 从data创建tensor 参数如下：

data: list/numpy

dtype: 默认与data一致

device：cuda/cpu

requires_grad: 是否需要梯度

pin_memory:是否存于锁业内存

In [8]:
arr = np.ones((3,3))
print(arr.dtype)
t = torch.tensor(arr)
print(t)

float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


1.2 torch.from_numpy(ndarray) 从numpy创建tensor

注意：torch.from_numpy创建的tensor与原numpy共享内存 修改其中一个 另一个也随之改动

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
t = torch.from_numpy(arr)
print(arr,t)
t[0,0] = -1
print(arr,t)
arr[1,1] = 8
print(arr,t)

[[1 2 3]
 [4 5 6]] tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
[[-1  2  3]
 [ 4  5  6]] tensor([[-1,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)
[[-1  2  3]
 [ 4  8  6]] tensor([[-1,  2,  3],
        [ 4,  8,  6]], dtype=torch.int32)


2.依据数值创建

2.1 torch.zeros() 根据size创建全0张量 参数如下：

size:张量形状 如(3,224,224)

out:输出的张量

layout:内存中布局形式

device and  requires_grad

In [19]:
out_t = torch.tensor([1])
print(out_t)
t = torch.zeros((3,3),out=out_t)
print(t)
print(out_t)
print(id(t),id(out_t),id(t)==id(out_t))

tensor([1])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
1683530510112 1683530510112 True


2.2 torch.zeros_like() torch.ones_like()根据input形状创建全0/1张量 params：

input:创建与input同形状的全0张量

dtype and layout and device and requires_grad

类似还有torch.full() torch.full_like() params:

size fill_value:填充的张量的值

In [23]:
t = torch.full((3,3),fill_value=3)
x = torch.full((3,3),fill_value=1)
t,x

(tensor([[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]),
 tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]))

torch.arange() 创建等差的1维张量 数值区间为[start,end) params:

start:起始值(包含)

end:结束值(不包含)

step：数列公差，默认为1

In [24]:
t = torch.arange(2,10,2)
t

tensor([2, 4, 6, 8])

torch.linspace() 创建均分的1维张量 数值区间为[start,end]

start:起始值(包含)

end:结束值(不包含)

steps：数列长度

步长step为 (end-start)/(steps-1)

In [27]:
t1 = torch.linspace(2,10,5)
t2 = torch.linspace(2,10,7)
t1,t2

(tensor([ 2.,  4.,  6.,  8., 10.]),
 tensor([ 2.0000,  3.3333,  4.6667,  6.0000,  7.3333,  8.6667, 10.0000]))

torch.logspace() 创建对数均分的1维张量 params：

start end steps base：对数函数的底 默认为10

torch.eye() 创建单位对角矩阵（2维张量 默认方阵 params：

n:行数 m:列数

3.依概率分布创建张量

3.1 torch.normal() 生成正态分布(高斯分布) params：

mean:均值  std:方差

四种模式

mean为标量  std为标量

mean为标量  std为张量

mean为张量  std为标量

mean为张量  std为张量

In [30]:
#mean为张量  std为张量
mean = torch.arange(1,5,dtype=torch.float)
std = torch.arange(1,5,dtype=torch.float)
t_normal = torch.normal(mean,std)
print(mean,std)
print(t_normal)

tensor([1., 2., 3., 4.]) tensor([1., 2., 3., 4.])
tensor([1.6680, 1.9197, 2.6898, 5.1459])


上面 1.6680 是通过mean=1 std=1的分布采样的来的

而5.1459是通过mean=5 std=5的分布采样得来的

In [31]:
#mean为标量  std为标量
t_normal = torch.normal(0,1,size=(4,))
print(t_normal)

tensor([ 0.8605,  0.7200,  0.1049, -0.5543])


In [35]:
#mean为张量  std为标量
#均值不一样 方差相同
mean = torch.arange(1,5,dtype=torch.float)
std = 1
t_normal = torch.normal(mean,std)
print(mean,std)
t_normal

tensor([1., 2., 3., 4.]) 1


tensor([1.1520, 1.5583, 3.1499, 3.3331])

In [40]:
#mean为标量  std为标量
#方差不一样 均值相同
std = torch.arange(1,5,dtype=torch.float)
mean = 0
t_normal = torch.normal(mean,std)
print(mean,std)
t_normal

0 tensor([1., 2., 3., 4.])


tensor([-0.7448,  1.2380,  0.7298,  7.3911])

3.2 torch.randn()  生成标准正态分布 params:

size: 张量的形状

torch.rand()

torch.rand_like()

[0,1)上的均匀分布

torch.randint()

torch.randint_like()

区间[low,high)生成整数均匀分布 params： size

torch.randperm() 生成从0到n-1的随机排列 params: 
 
n:张量的长度

torch.bernoulli() 以input为概率 生成伯努利分布（0-1分布/两点分布） params：

input:概率值