In [2]:
import torch
import numpy

# 张量拼接与切分

1.1 torch.cat() 将张量按维度dim进行拼接 params：

tensors：张量序列

dim：要拼接的维度

1.2 torch.stack() 在新创建的维度dim上进行拼接 会扩张维度 params：

tensors：张量序列

dim：要拼接的维度

In [3]:
t = torch.ones((4,6))
t

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [4]:
t_0 = torch.cat([t,t],dim=0)
t_1 = torch.cat([t,t],dim=1)
t_0,t_0.shape,t_1,t_1.shape
#不扩展维度 只是在原有矩阵的基础上增加长高

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]),
 torch.Size([8, 6]),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 torch.Size([4, 12]))

In [5]:
t_3 = torch.stack([t,t],dim=2)
t_4 = torch.stack([t,t,t],dim=2)
t_3,t_3.shape,t_4,t_4.shape
#会扩展维度 把两个二维矩阵拼接成三维 增加深度这一维

(tensor([[[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]]]),
 torch.Size([4, 6, 2]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 

In [6]:
t_s = torch.stack([t,t,t],dim=0)
t_s,t_s.shape

(tensor([[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]]),
 torch.Size([3, 4, 6]))

1.3 torch.chunk()  将张量按维度dim平均切分 返回张量列表 若不能整除 最后一份张量小于其他张量

params：

input；要切分的张量

chunks：要切分的份数

dim：要切分的维度

In [7]:
t_c = torch.chunk(t,2,0)
t_c1 = torch.chunk(t,2,1)
t_c2 = torch.chunk(t,3,1)
t,t_c,t_c1,t_c2

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]),
 (tensor([[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]),
  tensor([[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]])),
 (tensor([[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]),
  tensor([[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]])),
 (tensor([[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]]),
  tensor([[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]]),
  tensor([[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]])))

In [8]:
print(t)
for idx,t in enumerate(t_c1):
    print('第{}个张量，维度为{}'.format(idx,t.shape))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
第0个张量，维度为torch.Size([4, 3])
第1个张量，维度为torch.Size([4, 3])


1.4 torch.split() 将张量按维度dim进行切分 返回张量列表 params：

tensors:要切分的张量

split_size_or_sections:为int时表示每一份的长度 为list时 按list元素切分

dim：要切分的维度

In [9]:
t = torch.ones((4,6))
print(t.shape)
list = torch.split(t,1,dim=0)
for idx,t in enumerate(list):
    print('第{}个张量 {} 形状为{}'.format(idx+1,t,t.shape))

torch.Size([4, 6])
第1个张量 tensor([[1., 1., 1., 1., 1., 1.]]) 形状为torch.Size([1, 6])
第2个张量 tensor([[1., 1., 1., 1., 1., 1.]]) 形状为torch.Size([1, 6])
第3个张量 tensor([[1., 1., 1., 1., 1., 1.]]) 形状为torch.Size([1, 6])
第4个张量 tensor([[1., 1., 1., 1., 1., 1.]]) 形状为torch.Size([1, 6])


In [10]:
t = torch.ones((4,6))
print(t.shape)
list = torch.split(t,2,dim=0)
for idx,t in enumerate(list):
    print('第{}个张量 {} 形状为{}'.format(idx+1,t,t.shape))

torch.Size([4, 6])
第1个张量 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) 形状为torch.Size([2, 6])
第2个张量 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) 形状为torch.Size([2, 6])


In [11]:
t = torch.ones((4,6))
print(t.shape)
list = torch.split(t,2,dim=1)
for idx,t in enumerate(list):
    print('第{}个张量 {} 形状为{}'.format(idx+1,t,t.shape))

torch.Size([4, 6])
第1个张量 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) 形状为torch.Size([4, 2])
第2个张量 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) 形状为torch.Size([4, 2])
第3个张量 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) 形状为torch.Size([4, 2])


In [12]:
t = torch.ones((4,6))
print(t.shape)
list = torch.split(t,3,dim=1)
for idx,t in enumerate(list):
    print('第{}个张量 {} 形状为{}'.format(idx+1,t,t.shape))

torch.Size([4, 6])
第1个张量 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 形状为torch.Size([4, 3])
第2个张量 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 形状为torch.Size([4, 3])


In [13]:
t = torch.ones((4,6))
print(t.shape)
list = torch.split(t,4,dim=1)
for idx,t in enumerate(list):
    print('第{}个张量 {} 形状为{}'.format(idx+1,t,t.shape))

torch.Size([4, 6])
第1个张量 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 形状为torch.Size([4, 4])
第2个张量 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) 形状为torch.Size([4, 2])


In [14]:
t = torch.ones((4,6))
print(t.shape)
list = torch.split(t,[2,1,3],dim=1)
for idx,t in enumerate(list):
    print('第{}个张量 {} 形状为{}'.format(idx+1,t,t.shape))
    #list之和一定要和对应dim的长度相同 不然切不完会报错

torch.Size([4, 6])
第1个张量 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) 形状为torch.Size([4, 2])
第2个张量 tensor([[1.],
        [1.],
        [1.],
        [1.]]) 形状为torch.Size([4, 1])
第3个张量 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 形状为torch.Size([4, 3])


# 张量索引

2.1 torch.index_select() 在维度dim上 按index索引数据 返回根据index索引数据拼接的张量 params：

input：要索引的张量

dim：要索引的维度

index：要索引数据的序号

In [15]:
t = torch.randint(0,9,size=(3,3))
idx = torch.tensor([0,2],dtype=torch.long)
t_select = torch.index_select(t,dim=0,index=idx)
t,t_select

(tensor([[8, 4, 8],
         [6, 7, 1],
         [8, 8, 3]]),
 tensor([[8, 4, 8],
         [8, 8, 3]]))

In [16]:
t_select = torch.index_select(t,dim=1,index=idx)
t,t_select
#idx必须是torch.long类型的

(tensor([[8, 4, 8],
         [6, 7, 1],
         [8, 8, 3]]),
 tensor([[8, 8],
         [6, 1],
         [8, 3]]))

2.2 torch.masked_select() 按mask中的true进行索引 返回一维张量 params：

input:要索引的张量  

mask:与input形状相同的布尔类型张量

In [17]:
mask1 = t.le(5)
mask2 = t.ge(5)
#ge mean greater or equal le mean less or queal
#生成的是一维的 因为不清楚mask中true的具体个数 所以一维张量返回所有的
t1 = torch.masked_select(t,mask1)
t2 = torch.masked_select(t,mask2)
t1,t2

(tensor([4, 1, 3]), tensor([8, 8, 6, 7, 8, 8]))

# 张量变换

3.1 torch.reshape() 变换张量形状 当张量在内存中连续时 新张量与input共享内存数据 params：

input：要变换的张量

shape：新张量的形状

In [18]:
t1 = torch.reshape(t,(1,-1))
t,t.shape,t1,t1.shape

(tensor([[8, 4, 8],
         [6, 7, 1],
         [8, 8, 3]]),
 torch.Size([3, 3]),
 tensor([[8, 4, 8, 6, 7, 1, 8, 8, 3]]),
 torch.Size([1, 9]))

In [19]:
t[0,0] = 1024
t,t1
#共享内存

(tensor([[1024,    4,    8],
         [   6,    7,    1],
         [   8,    8,    3]]),
 tensor([[1024,    4,    8,    6,    7,    1,    8,    8,    3]]))

3.2 torch.transpose() 交换张量的两个维度 params：

input:要交换的张量

dim0：要交换的维度

dim1：要交换的维度

3.3 torch.t() 二维张量转置 对于矩阵而言 等价于 torch.transpose(input,1,0)


In [20]:
t = torch.randint(1,9,size=(2,4))
t1 = torch.transpose(t,dim0=0,dim1=1)
t,t.shape,t1,t1.shape

(tensor([[1, 4, 2, 8],
         [5, 1, 2, 4]]),
 torch.Size([2, 4]),
 tensor([[1, 5],
         [4, 1],
         [2, 2],
         [8, 4]]),
 torch.Size([4, 2]))

In [21]:
t2 = torch.t(t)
t2,t2.shape

(tensor([[1, 5],
         [4, 1],
         [2, 2],
         [8, 4]]),
 torch.Size([4, 2]))

In [22]:
t = torch.rand((2,3,4))
t1 = torch.transpose(t,1,2)
t2 = torch.transpose(t,0,2)
t,t.shape,t1,t1.shape,t2,t2.shape

(tensor([[[0.7564, 0.7267, 0.9752, 0.6333],
          [0.3655, 0.7822, 0.9801, 0.9474],
          [0.5055, 0.5060, 0.1989, 0.6586]],
 
         [[0.6402, 0.1760, 0.0632, 0.9340],
          [0.9895, 0.8237, 0.1121, 0.8900],
          [0.6555, 0.7817, 0.7128, 0.2255]]]),
 torch.Size([2, 3, 4]),
 tensor([[[0.7564, 0.3655, 0.5055],
          [0.7267, 0.7822, 0.5060],
          [0.9752, 0.9801, 0.1989],
          [0.6333, 0.9474, 0.6586]],
 
         [[0.6402, 0.9895, 0.6555],
          [0.1760, 0.8237, 0.7817],
          [0.0632, 0.1121, 0.7128],
          [0.9340, 0.8900, 0.2255]]]),
 torch.Size([2, 4, 3]),
 tensor([[[0.7564, 0.6402],
          [0.3655, 0.9895],
          [0.5055, 0.6555]],
 
         [[0.7267, 0.1760],
          [0.7822, 0.8237],
          [0.5060, 0.7817]],
 
         [[0.9752, 0.0632],
          [0.9801, 0.1121],
          [0.1989, 0.7128]],
 
         [[0.6333, 0.9340],
          [0.9474, 0.8900],
          [0.6586, 0.2255]]]),
 torch.Size([4, 3, 2]))

图像预处理 读进来C H W 要转换成 H W C 

3.4 torch.squeeze() 压缩长度为1的维度 params：

dim：若为none 移除所有长度为1的轴 若指定维度 当且仅当该轴长度为1时可以被移除

3.5 torch.unsqueeze() 依据dim拓展维度 params：

dim：扩展的维度

In [23]:
t = torch.rand((1,2,3,1))
t1 = torch.squeeze(t)
t2 = torch.squeeze(t,dim=0)
t3 = torch.squeeze(t,dim=1)
t,t.shape,t1,t1.shape,t2,t2.shape,t3,t3.shape

(tensor([[[[0.9578],
           [0.2025],
           [0.7577]],
 
          [[0.1533],
           [0.1176],
           [0.1901]]]]),
 torch.Size([1, 2, 3, 1]),
 tensor([[0.9578, 0.2025, 0.7577],
         [0.1533, 0.1176, 0.1901]]),
 torch.Size([2, 3]),
 tensor([[[0.9578],
          [0.2025],
          [0.7577]],
 
         [[0.1533],
          [0.1176],
          [0.1901]]]),
 torch.Size([2, 3, 1]),
 tensor([[[[0.9578],
           [0.2025],
           [0.7577]],
 
          [[0.1533],
           [0.1176],
           [0.1901]]]]),
 torch.Size([1, 2, 3, 1]))

# 张量数学运算

torch.add() 逐元素计算input+alpha*other params：

input：第一个张量

alpha：乘项因子

other：第二个张量

In [24]:
t = torch.randn((3,3))
t1 = torch.ones_like(t)
t_add = torch.add(t,10,t1)
t,t1,t_add 

C:\Users\18772\AppData\Local\Temp\ipykernel_3440\2117869421.py:3: UserWarning: This overload of add is deprecated:
	add(Tensor input, Number alpha, Tensor other, *, Tensor out)
Consider using one of the following signatures instead:
	add(Tensor input, Tensor other, *, Number alpha, Tensor out) (Triggered internally at C:\b\abs_abjetg6_iu\croot\pytorch_1686932924616\work\torch\csrc\utils\python_arg_parser.cpp:1485.)
  t_add = torch.add(t,10,t1)


(tensor([[ 1.3507, -0.8734, -0.5810],
         [ 0.1203, -1.4329,  0.0373],
         [ 0.2603, -0.4851,  0.9874]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[11.3507,  9.1266,  9.4190],
         [10.1203,  8.5671, 10.0373],
         [10.2603,  9.5149, 10.9874]]))